name: packer

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
env:
  PRODUCT_VERSION: "latest"

jobs:
  packer:
    runs-on: ubuntu-latest
    name: Run Packer
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - id: "auth"
        uses: "google-github-actions/auth@v2"
        with:
          credentials_json: "${{ secrets.GCP_CREDENTIALS }}"

      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v2"

      - name: "Use gcloud CLI"
        run: "gcloud info"

      - name: Setup `packer`
        uses: hashicorp/setup-packer@main
        id: setup
        with:
          version: ${{ env.PRODUCT_VERSION }}

      - name: Write secret to file
        run: |
          cat << EOF > ./image.auto.pkrvars.hcl
          ${{ secrets.PKRVARS }}
          EOF

      - name: Run `packer init`
        id: init
        run: "packer init ."

      - name: Build artifacts
        id: build
        run: |
          rm -rf webapp.zip
          zip -r webapp.zip . -x ".git/*" ".github/*" "node_modules/*"

      - name: Run `packer fmt`
        id: fmt
        run: "packer fmt -check ."

      - name: Run `packer validate`
        id: validate
        run: "packer validate ."

      - name: Create image in gcp
        id: image_create
        run: |
          packer build . | tee packer_build.txt
          IMAGE_ID= echo $( cat packer_build.txt | grep project | cut -d " " -f 12)
          echo $IMAGE_ID > packer_image_name.txt

      - name: Create instance template in gcp
        id: instance_create
        run: |
          IMAGE_NAME=$(cat packer_image_name.txt)
          gcloud compute instance-templates create webapp-from-git-temp \
          --instance-template-region="us-east1" \
          --tags="webapp" \
          --machine-type="n2-standard-2" \
          --region="us-east1" \
          --network-interface=network="cloud-demo-vpc",subnet="webapp" \
          --service-account=csye-demo-service-account@csye-6225-demo-413900.iam.gserviceaccount.com \
          --scopes=https://www.googleapis.com/auth/cloud-platform --tags=load-balanced-backend,csye-6225 \
          --maintenance-policy="MIGRATE" \
          --image-project="csye-6225-demo-413900" \
          --image=$IMAGE_NAME \
          --boot-disk-type="pd-standard"
