name: packer

on:
  push:
    branches:
      - main
env:
  PRODUCT_VERSION: "latest"

jobs:
  packer:
    runs-on: ubuntu-latest
    name: Run Packer
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - id: "auth"
        uses: "google-github-actions/auth@v2"
        with:
          credentials_json: "${{ secrets.GCP_CREDENTIALS }}"

      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v2"

      - name: "Use gcloud CLI"
        run: "gcloud info"

      - name: Setup `packer`
        uses: hashicorp/setup-packer@main
        id: setup
        with:
          version: ${{ env.PRODUCT_VERSION }}

      - name: Write secret to file
        run: |
          cat << EOF > ./image.auto.pkrvars.hcl
          ${{ secrets.PKRVARS }}
          EOF

      - name: Write secret to file
        run: |
          cat << EOF > ./.env
          ${{ secrets.ENV_FILE }}
          EOF

      - name: Write secret to file
        run: |
          cat << EOF > ./create_db.sql
          ${{ secrets.SQL_SCRIPT }}
          EOF

      - name: Run `packer init`
        id: init
        run: "packer init ."

      - name: Build artifacts
        id: build
        run: |
          rm -rf webapp.zip
          zip -r webapp.zip . -x ".git/*" ".github/*" "node_modules/*"

      - name: Run `packer fmt`
        id: fmt
        run: "packer fmt -check ."

      - name: Run `packer validate`
        id: validate
        run: "packer validate ."

      - name: Create image in gcp
        id: image_create
        run: packer build .
