name: packer

on:
  pull_request:
    branches:
      - main
env:
  PRODUCT_VERSION: "latest"

jobs:
  packer:
    runs-on: ubuntu-latest
    name: Run Packer
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup `packer`
        uses: hashicorp/setup-packer@main
        id: setup
        with:
          version: ${{ env.PRODUCT_VERSION }}
      - name: Write secret to file
        run: |
          cat << EOF > ./image.auto.pkrvars.hcl
          ${{ secrets.PKRVARS }}
          EOF
      - name: Build artifacts
        id: build
        run: |
          rm -rf webapp.zip
          zip -r webapp.zip . -x ".git/*" ".github/*" "node_modules/*"

      - name: Run `packer init`
        id: init
        run: "packer init ."

      - name: Run `packer fmt`
        id: fmt
        run: "packer fmt -check ."

      - name: Run `packer validate`
        id: validate
        run: "packer validate ."
